Repository B1ABOA/wedug, pull requests merged in 2024-08, with the labels that each got.

#3 mod: 디렉토리 구조 재설정
  src/main/java/com/b1aboa/wedug/config/temp.txt
  src/main/java/com/b1aboa/wedug/controller/temp.txt
  src/main/java/com/b1aboa/wedug/dto/temp.txt
  src/main/java/com/b1aboa/wedug/entity/temp.txt
  src/main/java/com/b1aboa/wedug/repository/temp.txt
  src/main/java/com/b1aboa/wedug/service/temp.txt
  src/main/java/config/temp.txt
  src/main/java/controller/temp.txt
  src/main/java/dto/temp.txt
  src/main/java/entity/temp.txt
  src/main/java/repository/temp.txt
  src/main/java/service/temp.txt
Labels: documentation

#5 Feature/setup resources
  build.gradle
  src/main/java/com/b1aboa/wedug/controller/HomeController.java
  src/main/resources/static/css/index.css
  src/main/resources/static/images/sinnosuke.png
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: ⚙ Setting

#6 Feature/connect external api
  src/main/java/com/b1aboa/wedug/controller/MapController.java
  src/main/java/com/b1aboa/wedug/service/MapService.java
  src/main/resources/templates/map.html
Labels: ✨ Feature

#8 refactor: .gitignore 재설정
  src/main/java/com/b1aboa/wedug/config/temp.txt
  src/main/java/com/b1aboa/wedug/dto/UserDTO.java
  src/main/java/com/b1aboa/wedug/entity/User.java
  src/main/java/com/b1aboa/wedug/repository/UserRepository.java
  src/main/java/com/b1aboa/wedug/service/UserService.java
  src/main/java/com/b1aboa/wedug/service/UserServiceImpl.java
Labels: 🔨 Refactor

#9 mod : 뷰 수정
  src/main/resources/static/css/common.css
  src/main/resources/static/js/tools.js
  src/main/resources/static/json/nation-code.json
  src/main/resources/templates/include/header-fragment.html
  src/main/resources/templates/include/navbar-fragment.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/user/user-find-password.html
  src/main/resources/templates/user/user-profile.html
  src/main/resources/templates/user/user-signup.html
Labels: 🎨 Style

#11 feat: UserServiceImpl에 createUser메서드 추가, UserController의 signUp기능 구현
  .gitignore
  build.gradle
  src/main/java/com/b1aboa/wedug/config/SecurityConfig.java
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/java/com/b1aboa/wedug/dto/UserDTO.java
  src/main/java/com/b1aboa/wedug/entity/Place.java
  src/main/java/com/b1aboa/wedug/entity/User.java
  src/main/java/com/b1aboa/wedug/service/UserService.java
  src/main/java/com/b1aboa/wedug/service/UserServiceImpl.java
Labels: ✨ Feature

#12 feat: 즐겨찾기 목록 보기 메소드 추가
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/java/com/b1aboa/wedug/entity/Favorite.java
  src/main/java/com/b1aboa/wedug/entity/Place.java
  src/main/java/com/b1aboa/wedug/repository/FavoriteRepository.java
  src/main/java/com/b1aboa/wedug/service/FavoriteService.java
  src/main/java/com/b1aboa/wedug/service/FavoriteServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature

#16 Feature/swagger
  build.gradle
  src/main/java/com/b1aboa/wedug/controller/DeptController.java
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/java/com/b1aboa/wedug/entity/Dept.java
  src/main/java/com/b1aboa/wedug/repository/DeptRepository.java
  src/main/java/com/b1aboa/wedug/service/DeptService.java
Labels: ⚙ Setting

#17 feat: favorites.html에 좋아요 목록 띄우기
  src/main/resources/templates/favorites/favorites.html
Labels: ✨ Feature

#18 Feature/search category
  src/main/java/com/b1aboa/wedug/controller/SearchController.java
  src/main/java/com/b1aboa/wedug/dto/PlaceDTO.java
  src/main/java/com/b1aboa/wedug/repository/MediaInfoRepository.java
  src/main/java/com/b1aboa/wedug/repository/PlaceRepository.java
  src/main/java/com/b1aboa/wedug/service/SearchService.java
  src/main/java/com/b1aboa/wedug/service/SearchServiceImpl.java
  src/main/resources/templates/map.html
  src/main/resources/templates/search/map-search.html
Labels: ✨ Feature

#19 feat: signup 기능 구현
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/java/com/b1aboa/wedug/dto/UserDTO.java
  src/main/java/com/b1aboa/wedug/entity/NationInfo.java
  src/main/java/com/b1aboa/wedug/entity/User.java
  src/main/java/com/b1aboa/wedug/repository/NationInfoRepository.java
  src/main/java/com/b1aboa/wedug/service/UserService.java
  src/main/java/com/b1aboa/wedug/service/UserServiceImpl.java
  src/main/resources/templates/user/user-signup.html
Labels: ✨ Feature

#20 style : 메인 화면 구성
  src/main/resources/static/css/common.css
  src/main/resources/templates/index.html
Labels: 🎨 Style

#21 feature/gradle
  build.gradle
Labels: ⚙ Setting

#24 Feature/view
  build.gradle
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/java/com/b1aboa/wedug/controller/HomeController.java
  src/main/java/com/b1aboa/wedug/controller/LoginController.java
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/java/com/b1aboa/wedug/controller/ViewController.java
  src/main/java/com/b1aboa/wedug/service/FavoriteServiceImpl.java
Labels: 🔨 Refactor

#25 feat/favorite: 즐겨찾기 없을 때 화면 구성
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/resources/static/css/common.css
  src/main/resources/templates/favorites/favorites.html
Labels: 🎨 Style

#26 Feature/search v3
  src/main/java/com/b1aboa/wedug/controller/PlaceController.java
  src/main/java/com/b1aboa/wedug/controller/SearchController.java
  src/main/java/com/b1aboa/wedug/controller/ViewController.java
  src/main/java/com/b1aboa/wedug/dto/PlaceDTO.java
  src/main/java/com/b1aboa/wedug/dto/PlaceSearchLogDTO.java
  src/main/java/com/b1aboa/wedug/entity/Place.java
  src/main/java/com/b1aboa/wedug/repository/PlaceInfoRepository.java
  src/main/java/com/b1aboa/wedug/repository/PlaceRepository.java
  src/main/java/com/b1aboa/wedug/service/PlaceService.java
  src/main/java/com/b1aboa/wedug/service/PlaceServiceImpl.java
  src/main/java/com/b1aboa/wedug/service/SearchService.java
  src/main/java/com/b1aboa/wedug/service/SearchServiceImpl.java
  src/main/resources/static/images/icons/heart-filled.svg
  src/main/resources/static/images/icons/heart.svg
  src/main/resources/templates/search/map-search.html
Labels: ✨ Feature, 🔨 Refactor, 🎨 Style

#29 Feature/log
  build.gradle
  src/main/java/com/b1aboa/wedug/dto/temp.txt
  src/main/java/com/b1aboa/wedug/filters/UserPlaceSearchLoggingFilter.java
  src/main/resources/log4j2.xml
  src/main/resources/static/js/jquery.3.6.0.min.js
  src/main/resources/static/js/jquery.preloaders.js
  src/main/resources/templates/include/head-meta-fragment.html
  src/main/resources/templates/include/navbar-fragment.html
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting

#30 mod: login api 수정
  src/main/java/com/b1aboa/wedug/controller/LoginController.java
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/java/com/b1aboa/wedug/jwt/LoginFilter.java
  src/main/resources/templates/login/login.html
  src/main/resources/templates/user/user-signup.html
Labels: 🐞 BugFix

#31 feature/view
  src/main/resources/static/css/common.css
  src/main/resources/static/images/icons/next.svg
  src/main/resources/static/images/icons/position.svg
  src/main/resources/static/images/icons/previous.svg
  src/main/resources/templates/search/map-search.html
Labels: 🎨 Style

#32 mod: 검색화면 팝업창 z-index 수정
  src/main/resources/templates/search/map-search.html
Labels: 🐞 BugFix

#33 feat: mypage 사용자정보 가져오기
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/java/com/b1aboa/wedug/service/UserService.java
  src/main/java/com/b1aboa/wedug/service/UserServiceImpl.java
  src/main/resources/templates/include/navbar-fragment.html
  src/main/resources/templates/user/user-profile.html
Labels: ✨ Feature

#34 feat/favorite
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/java/com/b1aboa/wedug/repository/FavoriteRepository.java
  src/main/java/com/b1aboa/wedug/service/FavoriteService.java
  src/main/java/com/b1aboa/wedug/service/FavoriteServiceImpl.java
  src/main/resources/templates/favorites/favorites.html
  src/main/resources/templates/include/navbar-fragment.html
  src/main/resources/templates/search/map-search.html
  src/test/java/com/b1aboa/wedug/repository/FavoriteRepositoryTest.java
Labels: ✨ Feature, 🔨 Refactor

#36 feature/jwtToken
  src/main/java/com/b1aboa/wedug/jwt/JWTUtil.java
  src/main/java/com/b1aboa/wedug/jwt/LoginFilter.java
Labels: 🐞 BugFix

#38 feature/logut
  src/main/java/com/b1aboa/wedug/controller/LoginController.java
  src/main/java/com/b1aboa/wedug/controller/UserController.java
  src/main/resources/templates/user/user-profile.html
Labels: ✨ Feature

#39 feat/favorite: url 정보 및 파리미터 처리 방식 변경
  src/main/java/com/b1aboa/wedug/controller/FavoritesController.java
  src/main/java/com/b1aboa/wedug/service/FavoriteServiceImpl.java
  src/main/resources/templates/favorites/favorites.html
  src/main/resources/templates/search/map-search.html
Labels: 🔨 Refactor

#41 feat: 즐겨찾기 로그 추가
  src/main/java/com/b1aboa/wedug/filters/UserFavoritesLoggingFilter.java
  src/main/resources/log4j2.xml
Labels: ✨ Feature

#42 docs/readme: 리드미 수정
  img_1.png
  readme.md
Labels: 📃 Docs

#43 docs/readme: readme 수정
  readme.md
Labels: 📃 Docs

#44 docs/readme: 첨부 이미지 수정
  readme.md
Labels: 📃 Docs

#45 feat: search 요청 header에 토큰 추가 토큰 유저 정보 log 저장하기
  src/main/java/com/b1aboa/wedug/controller/PlaceController.java
  src/main/resources/templates/search/map-search.html
Labels: ✨ Feature
